name: DiscordPlugin
main: buttondevteam.discordplugin.DiscordPlugin
version: 1.0
author: NorbiPeti
depend: [ButtonCore]
commands:
  discord:
website: 'https://github.com/TBMCPlugins/DiscordPlugin'
