name: Chroma-Discord
main: buttondevteam.discordplugin.DiscordPlugin
version: '${noprefix.version}'
author: NorbiPeti
depend: [ Chroma-Core ]
softdepend:
  - Essentials
commands:
  discord:
    description: 'Main command for Chroma-Discord'
website: 'https://github.com/TBMCPlugins/Chroma-Discord'
api-version: '1.13'
