name: Chroma-Discord
main: buttondevteam.discordplugin.DiscordPlugin
version: '1.0'
author: NorbiPeti
depend: [ChromaCore]
softdepend:
  - Essentials
commands:
  discord:
website: 'https://github.com/TBMCPlugins/Chroma-Discord'
api-version: '1.13'
